name: Main workflow

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - run: |
          sudo apt-get install -y libgtk2.0-dev build-essential

      - name: Checkout code
        uses: actions/checkout@v2

      - run: ./ROX-Filer/AppRun --compile
